# Generated by Django 4.0.3 on 2022-03-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
