# Generated by Django 4.0.3 on 2022-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='media/Pictures/default.jpg', upload_to='Pictures'),
        ),
    ]
